/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beatrizoliveira.view;
import br.beatrizoliveira.data.AlunoData;
import br.beatrizoliveira.model.Aluno;
import br.beatrizoliveira.model.Endereco;
import br.beatrizoliveira.model.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Beatriz Oliveira
 */
public class JDialog_addAluno extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_addAluno
     */
    private Aluno aluno;
    private AlunoData DAO;
    JTextField j = new JPasswordField();
    Border bordaPadrao =  j.getBorder();
    String acao;
    public JDialog_addAluno(java.awt.Frame parent, boolean modal,Aluno aluno,String acao) {
        super(parent, modal);
        initComponents();
        this.acao = acao;
        this.aluno = new Aluno();
        this.aluno = aluno;
        try {
            DAO = new AlunoData();
        } catch (Exception ex) {
            Logger.getLogger(JDialog_addAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private JDialog_addAluno(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDataNasc = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jTextField_peso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_altura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_sexoFeminino = new javax.swing.JRadioButton();
        jRadioButton_sexoMasculino = new javax.swing.JRadioButton();
        jLabelEndereco = new javax.swing.JLabel();
        jTextField_endereco = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_cidade = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jLabelUF = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_cep = new javax.swing.JTextField();
        jTextField_bairro = new javax.swing.JTextField();
        jTextField_uf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_profissao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_salvarCadastro = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jDateChooserDataNascimento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 410));
        jPanel1.setRequestFocusEnabled(false);

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDataNasc.setText("Data de Nascimento:");

        jTextField_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nomeFocusGained(evt);
            }
        });
        jTextField_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomeActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("Nome completo:");

        jLabelPeso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPeso.setText("Peso:");

        jTextField_peso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Altura:");

        jTextField_altura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_alturaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sexo:");

        jRadioButton_sexoFeminino.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_sexoFeminino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_sexoFeminino.setText("Fem.");
        jRadioButton_sexoFeminino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButton_sexoFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sexoFemininoActionPerformed(evt);
            }
        });

        jRadioButton_sexoMasculino.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_sexoMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_sexoMasculino.setText("Masc.");
        jRadioButton_sexoMasculino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButton_sexoMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_sexoMasculinoMouseClicked(evt);
            }
        });
        jRadioButton_sexoMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sexoMasculinoActionPerformed(evt);
            }
        });

        jLabelEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEndereco.setText("Endereço:");

        jTextField_endereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_enderecoActionPerformed(evt);
            }
        });

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumero.setText("nº:");

        jTextField_numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Bairro:");

        jTextField_cidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cidadeActionPerformed(evt);
            }
        });

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jLabelUF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUF.setText("UF:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("CEP:");

        jTextField_cep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cepActionPerformed(evt);
            }
        });

        jTextField_bairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bairroActionPerformed(evt);
            }
        });

        jTextField_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ufActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Telefone:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("E-mail:");

        jTextField_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Profissão:");

        jTextField_profissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_profissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_profissaoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(64, 85, 86));

        jLabel1.setBackground(new java.awt.Color(64, 85, 86));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Cadastrar novo(a) aluno(a)");
        jLabel1.setOpaque(true);

        jLabel_salvarCadastro.setBackground(new java.awt.Color(64, 85, 86));
        jLabel_salvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/salvar.png"))); // NOI18N
        jLabel_salvarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_salvarCadastro.setOpaque(true);
        jLabel_salvarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salvarCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_salvarCadastro)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel_salvarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCpf.setText("CPF:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_profissao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_email))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelDataNasc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabelPeso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_sexoMasculino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton_sexoFeminino))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelCpf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelEndereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNumero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelUF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNome))
                            .addComponent(jLabelCpf, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataNasc)
                        .addComponent(jLabelPeso)
                        .addComponent(jTextField_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jRadioButton_sexoMasculino)
                        .addComponent(jRadioButton_sexoFeminino))
                    .addComponent(jDateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jFormattedTextFieldTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelUF)
                    .addComponent(jTextField_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificarCampos() throws ParseException{
        
        //Border bordaPadrao = jTextField_cpf.getBorder();
        if(jTextField_nome.getText().equalsIgnoreCase("")){
            jTextField_nome.setBorder(new LineBorder(Color.RED));
        }
        if(jFormattedTextFieldCpf.getText().equalsIgnoreCase("")){
            jFormattedTextFieldCpf.setBorder(new LineBorder(Color.RED));            
        }
        if(jFormattedTextFieldTelefone.getText().equalsIgnoreCase("")){
            jFormattedTextFieldTelefone.setBorder(new LineBorder(Color.RED));            
        }
       
        if(!jTextField_nome.getText().equalsIgnoreCase("")&&
                !jFormattedTextFieldCpf.getText().equalsIgnoreCase("")&&
                !jFormattedTextFieldTelefone.getText().equalsIgnoreCase("")&&
                (jRadioButton_sexoMasculino.isSelected()||
                jRadioButton_sexoFeminino.isSelected())){
             return true;
           
        }else{
            return false;
        }
    }
    
    private void formatarCampo(JFormattedTextField campo, String formato){
      
        try {
            MaskFormatter mascara = new MaskFormatter(formato);
            mascara.install(campo);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo", "Erro", JOptionPane.ERROR);
        }
        }
        
    
    
    private void jTextField_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomeActionPerformed

    private void jTextField_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesoActionPerformed

    private void jTextField_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_alturaActionPerformed

    private void jRadioButton_sexoFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sexoFemininoActionPerformed
        if(jRadioButton_sexoMasculino.isSelected()){
            jRadioButton_sexoFeminino.setSelected(true);
            jRadioButton_sexoMasculino.setSelected(false);
        }

    }//GEN-LAST:event_jRadioButton_sexoFemininoActionPerformed

    private void jTextField_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_enderecoActionPerformed

    private void jTextField_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroActionPerformed

    private void jTextField_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cidadeActionPerformed

    private void jTextField_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cepActionPerformed

    private void jTextField_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bairroActionPerformed

    private void jTextField_ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ufActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jTextField_profissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_profissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_profissaoActionPerformed

    private void jLabel_salvarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salvarCadastroMouseClicked

        try { 
            if(verificarCampos()&&acao.equalsIgnoreCase("incluir")){
                Endereco endereco = new Endereco(jTextField_endereco.getText(),jTextField_numero.getText(),
                jTextField_bairro.getText(),jTextField_cidade.getText(),jTextField_uf.getText(),jTextField_cep.getText());
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            //Date dataNasc = formato.parse(jFormattedTextFieldDataNascimento.getText());
            Aluno aluno = new Aluno(jFormattedTextFieldCpf.getText(), jTextField_nome.getText(), jDateChooserDataNascimento.getDate(),
                    jRadioButton_sexoFeminino.isSelected()?"feminino":"masculino",
                    jFormattedTextFieldTelefone.getText(), jTextField_email.getText(),
                    Double.parseDouble(jTextField_peso.getText()), Double.parseDouble(jTextField_altura.getText()), 
       jTextField_profissao.getText(), endereco);
            
            //JOptionPane.showMessageDialog(rootPane, new java.sql.Date(aluno.getDataNasc().getTime()));
            if(DAO.cadastrar(aluno)){
                JOptionPane.showMessageDialog(rootPane, "Aluno cadastrado com sucesso");
            }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(JDialog_addAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(verificarCampos()&&acao.equalsIgnoreCase("alterar")){
                Endereco endereco = new Endereco(jTextField_endereco.getText(),jTextField_numero.getText(),
                        jTextField_bairro.getText(),jTextField_cidade.getText(),jTextField_uf.getText(),jTextField_cep.getText());
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                //Date dataNasc = formato.parse(jFormattedTextFieldDataNascimento.getText());
                Aluno aluno = new Aluno(jFormattedTextFieldCpf.getText(), jTextField_nome.getText(), jDateChooserDataNascimento.getDate(),
                        jRadioButton_sexoFeminino.isSelected()?"feminino":"masculino",
                        jFormattedTextFieldTelefone.getText(), jTextField_email.getText(),
                        Double.parseDouble(jTextField_peso.getText()), Double.parseDouble(jTextField_altura.getText()),
                        jTextField_profissao.getText(), endereco);
                try {
                    if(DAO.alterar(aluno)){
                        JOptionPane.showMessageDialog(rootPane, "Dados alterados com sucesso");
                    }
                    
                } catch (Exception ex) {
                    Logger.getLogger(JDialog_addAluno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(JDialog_addAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }//GEN-LAST:event_jLabel_salvarCadastroMouseClicked

    private void jRadioButton_sexoMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_sexoMasculinoMouseClicked
        

            
        
    }//GEN-LAST:event_jRadioButton_sexoMasculinoMouseClicked

    private void jRadioButton_sexoMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sexoMasculinoActionPerformed
        if(jRadioButton_sexoFeminino.isSelected()){
            jRadioButton_sexoMasculino.setSelected(true);
            jRadioButton_sexoFeminino.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton_sexoMasculinoActionPerformed

    private void jTextField_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nomeFocusGained
          jTextField_nome.setBorder(bordaPadrao);
    }//GEN-LAST:event_jTextField_nomeFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //formatarCampo(jFormattedTextFieldDataNascimento, "##/##/####");
        formatarCampo(jFormattedTextFieldCpf, "###.###.###-##");
        formatarCampo(jFormattedTextFieldTelefone, "(##)#########");
        
        if(acao.equalsIgnoreCase("alterar")){
            jTextField_nome.setText(aluno.getNome());
            jFormattedTextFieldCpf.setValue(aluno.getCpf());
            jDateChooserDataNascimento.setDate(aluno.getDataNasc());
            jTextField_peso.setText(String.valueOf(aluno.getPeso()));
            jTextField_altura.setText(String.valueOf(aluno.getAltura()));
            if(aluno.getSexo().equalsIgnoreCase("feminino")){
                jRadioButton_sexoFeminino.setSelected(true);
            }else{
                jRadioButton_sexoMasculino.setSelected(true);
            }
            jFormattedTextFieldTelefone.setValue(aluno.getTelefone());
            jTextField_email.setText(aluno.getEmail());
            jTextField_profissao.setText(aluno.getProfissao());
            jTextField_cep.setText(aluno.getEndereco().getCep());
            jTextField_endereco.setText(aluno.getEndereco().getRua());
            jTextField_uf.setText(aluno.getEndereco().getEstado());
            jTextField_numero.setText(aluno.getEndereco().getNumero());
            jTextField_bairro.setText(aluno.getEndereco().getBairro());
            jTextField_cidade.setText(aluno.getEndereco().getCidade());
            jTextField_uf.setText(aluno.getEndereco().getEstado());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_addAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_addAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_addAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_addAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_addAluno dialog = new JDialog_addAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JLabel jLabel_salvarCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_sexoFeminino;
    private javax.swing.JRadioButton jRadioButton_sexoMasculino;
    private javax.swing.JTextField jTextField_altura;
    private javax.swing.JTextField jTextField_bairro;
    private javax.swing.JTextField jTextField_cep;
    private javax.swing.JTextField jTextField_cidade;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_endereco;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_numero;
    private javax.swing.JTextField jTextField_peso;
    private javax.swing.JTextField jTextField_profissao;
    private javax.swing.JTextField jTextField_uf;
    // End of variables declaration//GEN-END:variables
}
