/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beatrizoliveira.view;

import br.beatrizoliveira.data.AlunoData;
import br.beatrizoliveira.data.TurmaData;
import br.beatrizoliveira.model.Aluno;
import br.beatrizoliveira.model.Turma;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beatriz Oliveira
 */
public class JFPrincipal extends javax.swing.JFrame {

    private Aluno obj;
    private AlunoData DAO;
    private TurmaData DAOTurma;
    private ArrayList<Aluno> listaraluno;
    private ArrayList<Turma> listaturma;
    Date data = new Date();
    private Object jDialog_addAlunoTurma;

    public JFPrincipal(GraphicsConfiguration gc) {
        super(gc);
    }
    /**
     * Creates new form JFPrincipal
     */CardLayout cardLayout;
    public JFPrincipal() {
        initComponents();
        jPanel1.setVisible(false);
        jPanel_alunos.setVisible(false);
        jPanel_turmas.setVisible(false);
        cardLayout = (CardLayout)jPanel1.getLayout(); 
        jPanel_alunos.setName("jPanel_alunos");
        jPanel_turmas.setName("jPanel_turmas");
        setExtendedState(MAXIMIZED_BOTH);
        
        obj = new Aluno();
        try {
            DAO = new AlunoData();
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            DAOTurma = new TurmaData();
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void listarAlunos(){
//        try {
//            listarecibos = DAO.listar();
//             NumberFormat nf = NumberFormat.getCurrencyInstance();
//            DefaultTableModel mp = (DefaultTableModel) jTrecibos.getModel();
//            mp.setNumRows(0);
//            for (Recibo r: listarecibos){
//                 String stringData = String.format("%1$td/%1$tm/%1$tY", r.getData());
//                 mp.addRow(new Object[]{""+stringData, r.getCpfResponsavel(), r.getNomeResponsavel(), 
//                     r.getCpfPaciente(), r.getNomePaciente(), r.getDescricao(), nf.format(r.getValor()),
//                 r.getSituacao()});
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(JDPesquisarRecibo.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
         try {
            listaraluno = DAO.listar(jTextField_pesquisaAlunos.getText());
            DefaultTableModel mp = (DefaultTableModel) jTable_alunos.getModel();
            mp.setNumRows(0);
            for (Aluno a: listaraluno){
                 String stringData = String.format("%1$td/%1$tm/%1$tY", a.getDataNasc());
                 mp.addRow(new String[]{""+a.getNome(), a.getCpf(), stringData, 
                     String.valueOf(a.getPeso()), String.valueOf(a.getAltura()), 
                     a.getSexo(), a.getTelefone(), a.getEmail(), a.getProfissao()});
            }
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void listarTurmas(){

         try {
            listaturma = DAOTurma.listar();
            DefaultTableModel mp = (DefaultTableModel) jTableTurma.getModel();
            mp.setNumRows(0);
            for (Turma t: listaturma){
                 
                 mp.addRow(new String[]{""+t.getId(), t.getDia(), t.getHorario(), 
                     t.getId_modalidade()});
            }
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_header = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_alunos = new javax.swing.JLabel();
        jLabel_turmas = new javax.swing.JLabel();
        jLabel_sair = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_alunos = new javax.swing.JPanel();
        jPanel_menualuno = new javax.swing.JPanel();
        jLabel_addAluno = new javax.swing.JLabel();
        jTextField_pesquisaAlunos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelEditarAluno = new javax.swing.JLabel();
        jLabelExcluirAluno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_alunos = new javax.swing.JTable();
        jPanel_turmas = new javax.swing.JPanel();
        jPanel_menuturmas = new javax.swing.JPanel();
        jTextField_pesquisaTurmas = new javax.swing.JTextField();
        jLabelEditarTurma = new javax.swing.JLabel();
        jLabelExcluirTurma = new javax.swing.JLabel();
        jLabel_addTurma = new javax.swing.JLabel();
        jLabelAddAlunoTurma = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(960, 800));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_header.setBackground(new java.awt.Color(64, 85, 86));
        jPanel_header.setPreferredSize(new java.awt.Dimension(1139, 65));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/logojoycebranco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1481, Short.MAX_VALUE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_header, java.awt.BorderLayout.PAGE_START);

        jPanel_menu.setBackground(new java.awt.Color(64, 85, 86));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(180, 540));

        jLabel_alunos.setBackground(new java.awt.Color(64, 85, 86));
        jLabel_alunos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_alunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_alunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alunos.setText("Alunos");
        jLabel_alunos.setOpaque(true);
        jLabel_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_alunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_alunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_alunosMouseExited(evt);
            }
        });

        jLabel_turmas.setBackground(new java.awt.Color(64, 85, 86));
        jLabel_turmas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_turmas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_turmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_turmas.setText("Turmas");
        jLabel_turmas.setOpaque(true);
        jLabel_turmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_turmasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_turmasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_turmasMouseExited(evt);
            }
        });

        jLabel_sair.setBackground(new java.awt.Color(64, 85, 86));
        jLabel_sair.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_sair.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sair.setText("Sair");
        jLabel_sair.setOpaque(true);
        jLabel_sair.setPreferredSize(new java.awt.Dimension(59, 25));
        jLabel_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_sairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_alunos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(jLabel_turmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addComponent(jLabel_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_turmas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addComponent(jLabel_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel_menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel_alunos.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_alunos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel_alunosComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel_alunosComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_alunosComponentShown(evt);
            }
        });

        jPanel_menualuno.setBackground(new java.awt.Color(215, 112, 113));
        jPanel_menualuno.setPreferredSize(new java.awt.Dimension(929, 60));

        jLabel_addAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/addaluno.png"))); // NOI18N
        jLabel_addAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addAlunoMouseClicked(evt);
            }
        });

        jTextField_pesquisaAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_pesquisaAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pesquisaAlunosKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabelEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/editar.png"))); // NOI18N
        jLabelEditarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarAlunoMouseClicked(evt);
            }
        });

        jLabelExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/excluir.png"))); // NOI18N
        jLabelExcluirAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExcluirAlunoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menualunoLayout = new javax.swing.GroupLayout(jPanel_menualuno);
        jPanel_menualuno.setLayout(jPanel_menualunoLayout);
        jPanel_menualunoLayout.setHorizontalGroup(
            jPanel_menualunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menualunoLayout.createSequentialGroup()
                .addComponent(jLabel_addAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_pesquisaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 887, Short.MAX_VALUE)
                .addComponent(jLabelEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel_menualunoLayout.setVerticalGroup(
            jPanel_menualunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menualunoLayout.createSequentialGroup()
                .addGroup(jPanel_menualunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_addAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_menualunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_menualunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_menualunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_pesquisaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabelExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Completo", "CPF", "Data Nasc.", "Peso", "Altura", "Sexo", "Telefone", "E-mail", "Profissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_alunos);

        javax.swing.GroupLayout jPanel_alunosLayout = new javax.swing.GroupLayout(jPanel_alunos);
        jPanel_alunos.setLayout(jPanel_alunosLayout);
        jPanel_alunosLayout.setHorizontalGroup(
            jPanel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_menualuno, javax.swing.GroupLayout.DEFAULT_SIZE, 1513, Short.MAX_VALUE)
            .addGroup(jPanel_alunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_alunosLayout.setVerticalGroup(
            jPanel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_alunosLayout.createSequentialGroup()
                .addComponent(jPanel_menualuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_alunos, "cardAlunos");

        jPanel_turmas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_menuturmas.setBackground(new java.awt.Color(215, 112, 113));
        jPanel_menuturmas.setPreferredSize(new java.awt.Dimension(929, 60));

        jTextField_pesquisaTurmas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_pesquisaTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesquisaTurmasActionPerformed(evt);
            }
        });
        jTextField_pesquisaTurmas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pesquisaTurmasKeyReleased(evt);
            }
        });

        jLabelEditarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/editar.png"))); // NOI18N
        jLabelEditarTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditarTurmaMouseClicked(evt);
            }
        });

        jLabelExcluirTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/excluir.png"))); // NOI18N
        jLabelExcluirTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExcluirTurmaMouseClicked(evt);
            }
        });

        jLabel_addTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/add.png"))); // NOI18N
        jLabel_addTurma.setToolTipText("Cadastrar turma");
        jLabel_addTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addTurmaMouseClicked(evt);
            }
        });

        jLabelAddAlunoTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beatrizoliveira/imagens/addaluno.png"))); // NOI18N
        jLabelAddAlunoTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddAlunoTurmaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuturmasLayout = new javax.swing.GroupLayout(jPanel_menuturmas);
        jPanel_menuturmas.setLayout(jPanel_menuturmasLayout);
        jPanel_menuturmasLayout.setHorizontalGroup(
            jPanel_menuturmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuturmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddAlunoTurma)
                .addGap(26, 26, 26)
                .addComponent(jTextField_pesquisaTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel_addTurma)
                .addGap(27, 27, 27)
                .addComponent(jLabelEditarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelExcluirTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_menuturmasLayout.setVerticalGroup(
            jPanel_menuturmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuturmasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_menuturmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menuturmasLayout.createSequentialGroup()
                        .addGroup(jPanel_menuturmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddAlunoTurma)
                            .addComponent(jLabelExcluirTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_addTurma)
                            .addComponent(jLabelEditarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menuturmasLayout.createSequentialGroup()
                        .addComponent(jTextField_pesquisaTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Dia", "Horário", "Modalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTurma);

        javax.swing.GroupLayout jPanel_turmasLayout = new javax.swing.GroupLayout(jPanel_turmas);
        jPanel_turmas.setLayout(jPanel_turmasLayout);
        jPanel_turmasLayout.setHorizontalGroup(
            jPanel_turmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_menuturmas, javax.swing.GroupLayout.DEFAULT_SIZE, 1513, Short.MAX_VALUE)
            .addGroup(jPanel_turmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(629, Short.MAX_VALUE))
        );
        jPanel_turmasLayout.setVerticalGroup(
            jPanel_turmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_turmasLayout.createSequentialGroup()
                .addComponent(jPanel_menuturmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel_turmas, "cardTurmas");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1709, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jLabel_turmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_turmasMouseClicked
        jPanel1.setVisible(true);
        jPanel_turmas.setVisible(true);
        jPanel_alunos.setVisible(false);
        cardLayout.show(jPanel1, "cardTurmas");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_turmasMouseClicked

    private void jLabel_alunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_alunosMouseEntered
        jLabel_alunos.setBackground(new Color(87, 116, 117));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_alunosMouseEntered

    private void jLabel_alunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_alunosMouseExited
        jLabel_alunos.setBackground(new Color(64, 85, 86));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_alunosMouseExited

    private void jLabel_turmasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_turmasMouseEntered
        jLabel_turmas.setBackground(new Color(87, 116, 117));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_turmasMouseEntered

    private void jLabel_turmasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_turmasMouseExited
        jLabel_turmas.setBackground(new Color(64, 85, 86));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_turmasMouseExited

    private void jLabel_alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_alunosMouseClicked
        jPanel1.setVisible(true);
        jPanel_alunos.setVisible(true);
        jPanel_turmas.setVisible(false);
        cardLayout.show(jPanel1, "cardAlunos");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_alunosMouseClicked

    private void jLabel_addAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addAlunoMouseClicked
        JDialog_addAluno jDialog_addAluno = new JDialog_addAluno(this, rootPaneCheckingEnabled,null,"incluir");
        jDialog_addAluno.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel_addAlunoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listarAlunos();
        listarTurmas();
       
    }//GEN-LAST:event_formWindowOpened

    private void jPanel_alunosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_alunosComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_alunosComponentResized

    private void jPanel_alunosComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_alunosComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_alunosComponentMoved

    private void jPanel_alunosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_alunosComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel_alunosComponentShown

    private void jLabel_addTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addTurmaMouseClicked
        JDialog_addTurma jDialog_addTurma = new JDialog_addTurma(this, rootPaneCheckingEnabled);
        jDialog_addTurma.setVisible(true);
    }//GEN-LAST:event_jLabel_addTurmaMouseClicked

    private void jLabel_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sairMouseEntered
        jLabel_sair.setBackground(new Color(87, 116, 117));
    }//GEN-LAST:event_jLabel_sairMouseEntered

    private void jLabel_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sairMouseExited
        jLabel_sair.setBackground(new Color(64, 85, 86));
    }//GEN-LAST:event_jLabel_sairMouseExited

    private void jLabel_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sairMouseClicked
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja deslogar do sistema? ","Logout",JOptionPane.YES_NO_OPTION);
        if(resposta==0){
        JFLogin jFLogin = new JFLogin();
        jFLogin.setVisible(true);
        this.dispose();
        
        }
    }//GEN-LAST:event_jLabel_sairMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try {
            listaraluno = DAO.listar(jTextField_pesquisaAlunos.getText());
            DefaultTableModel mp = (DefaultTableModel) jTable_alunos.getModel();
            mp.setNumRows(0);
            for (Aluno a: listaraluno){
                 String stringData = String.format("%1$td/%1$tm/%1$tY", a.getDataNasc());
                 mp.addRow(new String[]{""+a.getNome(), a.getCpf(), stringData, 
                     String.valueOf(a.getPeso()), String.valueOf(a.getAltura()), 
                     a.getSexo(), a.getTelefone(), a.getEmail(), a.getProfissao()});
            }
        } catch (Exception ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarTurmas();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTextField_pesquisaAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pesquisaAlunosKeyReleased
       listarAlunos();
    }//GEN-LAST:event_jTextField_pesquisaAlunosKeyReleased

    private void jLabelExcluirAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExcluirAlunoMouseClicked
        if (jTable_alunos.getSelectedRow() > -1) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o aluno?", "", JOptionPane.YES_NO_OPTION) == 0) {
                try {
                    if (DAO.excluir(listaraluno.get(jTable_alunos.getSelectedRow()).getCpf())) {
                        JOptionPane.showMessageDialog(rootPane, "Aluno excluído com sucesso");
                    }

                } catch (Exception ex) {
                    Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione algum aluno");
        }
    }//GEN-LAST:event_jLabelExcluirAlunoMouseClicked

    private void jLabelEditarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarAlunoMouseClicked
      if (jTable_alunos.getSelectedRow() > -1) {
              JDialog_addAluno jDialog_addAluno = new JDialog_addAluno(this, rootPaneCheckingEnabled,
                      listaraluno.get(jTable_alunos.getSelectedRow()), "alterar");
              jDialog_addAluno.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione algum aluno");
        }
    }//GEN-LAST:event_jLabelEditarAlunoMouseClicked

    private void jTextField_pesquisaTurmasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pesquisaTurmasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesquisaTurmasKeyReleased

    private void jTextField_pesquisaTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesquisaTurmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesquisaTurmasActionPerformed

    private void jLabelEditarTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditarTurmaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEditarTurmaMouseClicked

    private void jLabelExcluirTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExcluirTurmaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExcluirTurmaMouseClicked

    private void jLabelAddAlunoTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddAlunoTurmaMouseClicked
        JDialog_addAlunoTurma jDialog_addAlunoTurma = new JDialog_addAlunoTurma(this, rootPaneCheckingEnabled);
        jDialog_addAlunoTurma.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabelAddAlunoTurmaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddAlunoTurma;
    private javax.swing.JLabel jLabelEditarAluno;
    private javax.swing.JLabel jLabelEditarTurma;
    private javax.swing.JLabel jLabelExcluirAluno;
    private javax.swing.JLabel jLabelExcluirTurma;
    private javax.swing.JLabel jLabel_addAluno;
    private javax.swing.JLabel jLabel_addTurma;
    private javax.swing.JLabel jLabel_alunos;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_sair;
    private javax.swing.JLabel jLabel_turmas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_alunos;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_menualuno;
    private javax.swing.JPanel jPanel_menuturmas;
    private javax.swing.JPanel jPanel_turmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTurma;
    private javax.swing.JTable jTable_alunos;
    private javax.swing.JTextField jTextField_pesquisaAlunos;
    private javax.swing.JTextField jTextField_pesquisaTurmas;
    // End of variables declaration//GEN-END:variables
}
